# Generated by Django 4.2.5 on 2023-09-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='utc_time',
            field=models.DateTimeField(verbose_name='2023-09-11T16:03:16Z'),
        ),
    ]
